### PR TITLE
Close #21: Raise an ActiveCMIS::HTTPError::ClientError in the case of th...

### LINKED ISSUE #21: undefined method `request_uri' for #<URI::Generic:0x10a2a30e0 URL:test>
If the URL passed from the configuration is not a valid URL, URI raise an exception not managed by activecmis where it should.

cmis.yml
```yaml
development:
  server_url: "test"
```

initializers/active_cmis.rb
```ruby
require "active_cmis"

begin
  Fundlook::Repositories::Alfresco.repository = ActiveCMIS.load_config(Rails.env, File.join(Rails.root, "config", "cmis.yml"))
rescue Timeout::Error, SocketError => error
  Rails.logger.warn "Error while connecting with CMIS: #{error.message}"
end
```

```
thin start
>> Using rails adapter
/Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/bundler/gems/activecmis-7f99b627339b/lib/active_cmis/internal/connection.rb:45:in `get': undefined method `request_uri' for #<URI::Generic:0x10a2a30e0 URL:test> (NoMethodError)
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/bundler/gems/activecmis-7f99b627339b/lib/active_cmis/internal/connection.rb:70:in `get_xml'
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/bundler/gems/activecmis-7f99b627339b/lib/active_cmis/server.rb:107:in `repository_info__uncached'
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/bundler/gems/activecmis-7f99b627339b/lib/active_cmis/internal/caching.rb:28:in `repository_info'
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/bundler/gems/activecmis-7f99b627339b/lib/active_cmis/server.rb:79:in `uncached_repository'
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/bundler/gems/activecmis-7f99b627339b/lib/active_cmis/server.rb:74:in `repository'
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/bundler/gems/activecmis-7f99b627339b/lib/active_cmis/active_cmis.rb:49:in `connect'
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/bundler/gems/activecmis-7f99b627339b/lib/active_cmis/active_cmis.rb:79:in `load_config'
	from /Users/guillaumeh/Developments/fundlook/config/initializers/active_cmis.rb:4
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:171:in `load_without_new_constant_marking'
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:171:in `load'
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:547:in `new_constants_in'
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/gems/activesupport-2.3.18/lib/active_support/dependencies.rb:171:in `load'
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/gems/rails-2.3.18/lib/initializer.rb:622:in `load_application_initializers'
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/gems/rails-2.3.18/lib/initializer.rb:621:in `each'
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/gems/rails-2.3.18/lib/initializer.rb:621:in `load_application_initializers'
	from /Users/guillaumeh/.rvm/gems/ree-1.8.7-2012.02@fundlook/gems/rails-2.3.18/lib/initializer.rb:176:in `process'
```

### PR DESCRIPTION
**Pull request by zedtux**
This pull request implement the possibility to set the timeout to be used by the `Net::HTTP` object.

### CODE REVIEW

**Comment by zedtux** [comment]
@joerixaop any chance you accept/reject my pull request ?

**Comment by zedtux** [comment]
@joerixaop any chance you accept/reject my PR ?

**Comment by joerixaop** [comment]
I've done so and released a new version. But I don't use this gem anymore, so maintenance related tasks are really a low priority for me at the moment.

**Comment by CloCkWeRX** [comment]
Re maintenance, want to open it up to a few other collaborators that have added pull requests?

**Pull request merged**
